<a href="https://colab.research.google.com/github/AndreLuisdePaula/StatsCWBe-Sports/blob/main/Stats_CWBe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importação das bibliotecas

from bs4 import BeautifulSoup
import requests
import pandas as pd
import datetime
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#criação da lista de jogadores que eu gostaria de obter os dados

ids = ['CWBe gal3god', 'CWBe TilaPINHA', 'CWBe Che4TooS', 'CWBe fcjjunior', 'CWBe Russi', 'ianL']
tags = ['CWB', 'CWB', 'Cwb', 'Cwb', '2295', 'BR1']

In [ ]:
#variável que armazena a data atual
data_atual = datetime.datetime.now().strftime("%d/%m/%Y")
data_atual = data_atual.replace("/", '-')
data_atual

'30-04-2023'

In [ ]:
#listas para armazenar os resultados
nomes = []
elos = []
horas_jogadas = []
partidas_jogadas = []
dano_por_round = []
kd_ratio = []
perc_hs = []
perc_vitorias = []
vitorias = []
kast = []
kills = []
deaths = []
assists = []
kad_ratio = []
kpr = []
first_blood = []
aces = []

In [ ]:
#caso eu tenha uma lista criada, eu uso essas funções para limpar as listas e adicionar dados atualizados

nomes.clear()
elos.clear()
horas_jogadas.clear()
partidas_jogadas.clear()
dano_por_round.clear()
kd_ratio.clear()
perc_hs.clear()
perc_vitorias.clear()
vitorias.clear()
kast.clear()
kills.clear()
deaths.clear()
assists.clear()
kad_ratio.clear()
kpr.clear()
first_blood.clear()
aces.clear()

In [ ]:
#uso a biblioteca requests para acessar o site e obter os dados pela biblioteca BeautifulSoup

for id, tag in zip(ids, tags):
  site = f'https://tracker.gg/valorant/profile/riot/{id}%23{tag}/overview'
  page = requests.get(site)
  html_contents = page.text
  soup = BeautifulSoup(html_contents, 'html.parser')

  nome = soup.find("span", class_="trn-ign__username").get_text().strip()
  elo = soup.find("span", class_="stat__value").get_text()
  horas = soup.find("span", class_='playtime').get_text().split('Play Time')[0].strip()
  partidas = soup.find("span", class_="matches").get_text().split('Matches')[0].strip()
  dano = soup.find("div", class_='numbers').get_text().split('Damage/Round')[1]
  kd = soup.find_all("div", class_='numbers')[1].get_text().split('K/D Ratio')[1]
  hs = soup.find_all("div", class_='numbers')[2].get_text().split('Headshot%')[1].split('%')[0]
  vitoria = soup.find_all("div", class_='numbers')[3].get_text().split('Win %')[1]
  tvitoria = soup.find_all("div", class_='numbers')[4].get_text().split('Wins')[1].split('Top')[0].split('Bottom')[0]
  kast_ = soup.find_all("div", class_='numbers')[5].get_text().split('KAST')[1]
  kill = soup.find_all("div", class_='numbers')[7].get_text().split('Kills')[1].split('Top')[0].split('Bottom')[0].replace(',', '')
  death = soup.find_all("div", class_='numbers')[8].get_text().split('Deaths')[1].replace(',', '')
  assist = soup.find_all("div", class_='numbers')[9].get_text().split('Assists')[1]
  kad = soup.find_all("div", class_='numbers')[11].get_text().split('KAD Ratio')[1]
  kpr_ = soup.find_all("div", class_='numbers')[12].get_text().split('Kills/Round')[1]
  first_blood_ = soup.find_all("div", class_='numbers')[13].get_text().split('First Bloods')[1]
  aces_ = soup.find_all("div", class_='numbers')[15].get_text().split('Aces')[1]

  nomes.append(nome)
  elos.append(elo)
  horas_jogadas.append(horas)
  partidas_jogadas.append(partidas)
  dano_por_round.append(dano[0:5])
  kd_ratio.append(kd[0:4])
  perc_hs.append(hs[0:4])
  perc_vitorias.append(vitoria[0:4])
  vitorias.append(tvitoria[0:2])
  kast.append(kast_[0:4])
  kills.append(kill)
  deaths.append(death)
  assists.append(assist)
  kad_ratio.append(kad)
  kpr.append(kpr_)
  first_blood.append(first_blood_)
  aces.append(aces_)

In [ ]:
#crio uma array e faço a conversão para um dataframe

array = {'Nome': nomes, 'Elo': elos, 'Horas Jogadas': horas_jogadas, 'Partidas Jogadas': partidas_jogadas, 'Dano por Round': dano_por_round, 'KD Ratio': kd_ratio, '% HS': perc_hs, '% Vitorias': perc_vitorias,
      'Vitorias': vitorias, 'KAST': kast, 'Abates': kills, 'Mortes': deaths, 'Assistências': assists, 'KAD Ratio': kad_ratio, 'Abates por Round': kpr, 'First Blood': first_blood, 'Aces': aces, 'Data': data_atual}

df = pd.DataFrame(array)
df

,Nome,Elo,Horas Jogadas,Partidas Jogadas,Dano por Round,KD Ratio,% HS,% Vitorias,Vitorias,KAST,Abates,Mortes,Assistências,KAD Ratio,Abates por Round,First Blood,Aces,Data
0,CWBe gal3god,Gold 2,1h 52m,3,174.5,1.43,19.9,66.7,2,76.6,66,46,26,2.00,1.0,10,1,30-04-2023
1,CWBe TilaPINHA,Gold 1,2h 33m,4,144.8,1.02,11.3,50.0,2,70.2,67,66,18,1.29,0.8,11,0,30-04-2023
2,CWBe Che4TooS,Gold 1,9h 14m,14,135.5,0.91,11.6,28.6,4,71.1,203,222,117,1.44,0.7,16,0,30-04-2023
3,CWBe fcjjunior,Silver 2,15h,25,134.2,0.93,12.1,36.0,9,67.6,364,391,141,1.29,0.7,45,0,30-04-2023
4,CWBe Russi,Unranked,37m 58s,1,109.7,1.00,9.7,100.,1,66.7,14,14,6,1.43,0.6,1,0,30-04-2023
5,ianL,Platinum 3,8h 23m,15,141.7,1.12,16.9,60.0,9,74.4,236,211,90,1.55,0.8,34,0,30-04-2023

In [ ]:
#uso a funções lambdas para converter alguns tipos de dados

df['Partidas Jogadas'] = df['Partidas Jogadas'].apply(lambda x: int(x))
df['Dano por Round'] = df['Dano por Round'].apply(lambda x: float(x))
df['KD Ratio'] = df['KD Ratio'].apply(lambda x: float(x))
df['% HS'] = df['% HS'].apply(lambda x: float(x))
df['% Vitorias'] = df['% Vitorias'].apply(lambda x: float(x))
df['Vitorias'] = df['Vitorias'].apply(lambda x: int(x))
df['KAST'] = df['KAST'].apply(lambda x: float(x))
df['Abates'] = df['Abates'].apply(lambda x: int(x))
df['Mortes'] = df['Mortes'].apply(lambda x: int(x))
df['Assistências'] = df['Assistências'].apply(lambda x: int(x))
df['KAD Ratio'] = df['KAD Ratio'].apply(lambda x: float(x))
df['Abates por Round'] = df['Abates por Round'].apply(lambda x: float(x))
df['First Blood'] = df['First Blood'].apply(lambda x: int(x))
df['Aces'] = df['Aces'].apply(lambda x: int(x))

In [ ]:
#converto para o formato .csv e salvo no Google Drive

df.to_csv(f'/content/drive/My Drive/Stats {data_atual}.csv', index=False)